home/urls.py
from django.urls import path
from home import views

urlpatterns = [
    path("", views.home, name="home"),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("projects/", include("projects.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

virtual_bookshelf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("home.urls")),
    path("bookshelf/", include("bookshelf.urls")),
    path("user/", include("user.urls")),
    path("friend_request/", include("friend_request.urls")),
    path("loan_request/", include("loan_request.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookshelf/models.py
import uuid

from django.db import models

PRIVATE = "0"
FRIENDS = "1"
PUBLIC = "2"

VISIBILITY_CHOICES = [
    (PRIVATE, "private"),
    (FRIENDS, "friends"),
    (PUBLIC, "public"),
]

GENRES = [
        "", "romance", "non-fiction", "thriller", "fantasy"
    ]

GENRES = [(v.lower(), v.title()) for v in GENRES]

LANGUAGES = [
        "", "german", "english", "spanish", "italian"
    ]

LANGUAGES = [(v.lower(), v.title()) for v in LANGUAGES]

class Book(models.Model):
    """
    Definition of the Book datamodel
    """

    bookID = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    isbn = models.CharField(max_length=17, unique=True) #13 characters with 4 hyphens
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    #genre = models.CharField(max_length=50, blank=True, null=True)
    genre = models.CharField(
        choices=GENRES,
        default="",
    )
    language = models.CharField(
            choices=LANGUAGES,
            default="",
        )
    year_of_publication = models.IntegerField(blank=True, null=True)
    visibility = models.CharField(
        max_length=1,
        choices=VISIBILITY_CHOICES,
        default=PUBLIC,
    )
    borrowable = models.BooleanField(default=True)
    ownerID = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    shelfID = models.ForeignKey('Shelf', on_delete=models.CASCADE)
    coverURL = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title


class Shelf(models.Model):
    """
    Definition of the Bookshelf datamodel
    """
    shelfID = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    ownerID = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)

    def __str__(self):
        return self.name

home/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    """
    Defines the User datamodel
    """
    userID = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username = models.CharField(max_length = 36, unique=True)
    password = models.CharField(max_length = 100)
    email = models.CharField(max_length = 254, unique=True)
    admin = models.BooleanField(default=False)
    groups = None
    user_permissions = None

    def __str__(self):
        return self.username

home/views.py
from django.shortcuts import render

def home(request):
    return render(request, "pages/home.html", {})

templates/pages/bookshelf_view_shelf.html
{% extends "base.html" %}

{% block page_content %}
    {% include "pages/bookshelves_book_row.html" with bookshelf=bookshelf %}
{% endblock page_content %}

templates/pages/bookshelves_book_row.html
<div class="book-row">
    <fieldset>
        <legend>
            <h3>{{ bookshelf.name }}</h3>
        </legend>
        <div class="carousel">
            {% for book in bookshelf.book_set.all %}
            <div class="book">
                <a href="/bookshelf/{{ bookshelf.shelfID }}/{{ book.isbn }}">
                    <img src={{ book.coverURL }}>
                </a>
                <h4>{{ book.title }}</h4>
                <p>Author: {{ book.author }}</p>
                <!-- Add more book details as needed -->
            </div>
            {% endfor %}
        </fieldset>
    <a href="{% url 'new_book' bookshelf.shelfID %}">Add Book</a>

</div>
</div>

templates/pages/bookshelves_overview.html
{% extends "base.html" %}

{% block page_content %}

  <a href="{% url 'add-bookshelf' %}">Add Bookshelf</a>

    {% for bookshelf in shelves %}
        {% include "pages/bookshelves_book_row.html" with bookshelf=bookshelf %}
    {% endfor %}
{% endblock page_content %}

templates/pages/create_shelf.html
{% extends "base.html" %}

{% block page_content %}
<h2>
  {% if is_edit %}
    Edit bookshelf
  {% else %}
    Add a new bookshelf
  {% endif %}
</h2>

<form class="contact-form" method="post">
  {% csrf_token %}

  <label for="name">Bookshelf name:</label><br>
  <input
    type="text"
    id="name"
    name="name"
    value="{{ shelf.name|default:'' }}"
    required
  ><br><br>

  <label for="latitude">Latitude:</label><br>
  <input
    type="number"
    id="latitude"
    name="latitude"
    step="0.000001"
    value="{{ shelf.latitude|default:'' }}"
    required
  ><br><br>

  <label for="longitude">Longitude:</label><br>
  <input
    type="number"
    id="longitude"
    name="longitude"
    step="0.000001"
    value="{{ shelf.longitude|default:'' }}"
    required
  ><br><br>

  <input type="submit" value="Save">
</form>

{% endblock page_content %}

templates/pages/edit_book.html
{% extends "base.html" %}

{% block page_content %}
<h2>
    {% if is_edit %}
    Edit book
    {% else %}
    Add a new book
    {% endif %}
</h2>
<h3>
    <a href="/user/{{ shelf.ownerID }}">{{ shelf.ownerID }}</a>
    &gt
    <a href="/bookshelf/{{ shelf.shelfID }}">{{ shelf.name }}</a>
</h3>


<form class="contact-form" method = "post">
    {% csrf_token %}
    <label for="title">Titel:</label><br>
    <input type="text" id="title" name="title" value="{{ book.title|default:'' }}" required><br>
    <label for="author">Author:</label><br>
    <input type="text" id="author" name="author" value="{{ book.author|default:'' }}" required>
    <label for="isbn">ISBN:</label><br>
    <input type="text" id="isbn" name="isbn" value="{{ book.isbn|default:'' }}" required>
    <label for="genre">Genre:</label><br>
    <select name="genre" id="genre" >
        {% for genre in genres %}
        <option value="{{ genre }}" {% if genre == current_genre or '' %}selected{% endif %}>{{ genre }}</option>
        {% endfor %}
    </select>
    <label for="language">Language:</label><br>
    <select name="language" id="language" >
        {% for language in languages %}
        <option value="{{ language }}" {% if language == current_language or '' %}selected{% endif %}>{{ language }}</option>
        {% endfor %}
    </select>
    <label for="pubYear">Pub. year:</label><br>
    <input type="number" id="pubYear" name="pubYear" value="{{ book.year_of_publication|default:'' }}"><br>
    <label for="borrowable">Borrowable?</label><br>
    <input type="checkbox" id="borrowable" name="borrowable" checked><br>
    <label for="visibility">Visibility:</label><br>
    <select name="visibility" id="visibility">
        <option value="public">Public</option>
        <option value="friends">Friends</option>
        <option value="private">Private</option>
    </select>
    <label for="coverURL">URL to cover:</label>
    <input type="url" id="coverURL" name="coverURL" value="{{ book.coverURL|default:'' }}">
    <input type="submit" value="Save">
</form>

{% endblock page_content %}

templates/pages/friend_requests_overview.html
{% extends "base.html" %}

{% block page_content %}
    <h1>Friend Requests:</h1>
{% endblock page_content %}

templates/pages/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block page_content %}
    <h1>Home</h1>

    <h2> Hi {{ user.username }}! </h2>
    <a href="/bookshelf/">Bookshelves</a> </br>
    <a href="/friend_request/">Friend Requests</a> </br>
    <a href="/loan_request/">Loan Requests</a>
    <p><a href="{% url 'password_change' %}">Change Password</a></p>
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Log Out</button>
    </form>

    {% endblock page_content %}

templates/pages/loan_requests_overview.html
{% extends "base.html" %}

{% block page_content %}
    <h1>Loan Requests:</h1>
{% endblock page_content %}

templates/pages/new_book_done.html
{% extends "base.html" %}

{% block page_content %}
{% if is_edit %}
<p>Book successfully edited!</p>
{% else %}
<p>Book successfully created!!</p>
{% endif %}
<p><a href="{% url 'bookshelves' %}">Back to my bookshelves</a></p>
{% endblock page_content %}

templates/pages/view_book.html
{% extends "base.html" %}

{% block page_content %}
    <h3> 
        <a href="/user/{{ shelf.ownerID }}">{{ shelf.ownerID }}</a> 
        &gt 
        <a href="/bookshelf/{{ shelf.shelfID }}">{{ shelf.name }}</a>
    </h3>
    <h1>{{ book.title }}</h1>
    <img class="bookcover" src={{ book.coverURL }}>
    <p> Author: {{ book.author }} </p>
    <p> ISBN: {{ book.isbn }} </p>
    <p> Genre: {{ current_genre }}</p>
    <p> Language: {{ current_language }}</p>
    <p> Pub. date: {{ book.year_of_publication }}</p>
    <p> Borrowable: {{ book.borrowable }}</p>
    <p> Visibility: {{ book.get_visibility_display }}</p>

<a href="{% url 'edit_book' shelf.shelfID book.bookID %}">Edit</a>


{% endblock page_content %}